# Generated by Django 6.1 on 2026-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('full_name', models.CharField(max_length=300)),
                ('profile_picture', models.URLField(blank=True)),
                ('google_locale', models.CharField(blank=True, max_length=20)),
                ('google_hosted_domain', models.CharField(blank=True, max_length=255)),
                ('gmail_connected', models.BooleanField(default=False)),
                ('gmail_permission_granted', models.BooleanField(default=False)),
                ('gmail_scopes', models.JSONField(blank=True, default=list)),
                ('gmail_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
