"""
Django settings for the DevForge project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


# =========================================================
# Environment & Base Directory
# =========================================================

# Load environment variables from .env during local development.
load_dotenv()

# Project root directory.
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# Security
# =========================================================

# Keep the secret key in .env locally and Render Environment Variables in production.
SECRET_KEY = os.getenv("SECRET_KEY")

# True for local development, False for production.
DEBUG = os.getenv("DEBUG", "False") == "True"

# Hosts allowed to access the Django application.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]

# Trusted origins for CSRF-protected requests, including the Render HTTPS domain.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# =========================================================
# Applications
# =========================================================

INSTALLED_APPS = [
    # Django built-in applications.
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Django REST Framework.
    "rest_framework",

    # DevForge applications.
    "apps.accounts",
    "apps.emails",
    "apps.location",
    "apps.ai",
    "apps.files",
    "apps.reports",

    # Django Sites framework.
    "django.contrib.sites",

    # Django Allauth and Google authentication.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]


# =========================================================
# Middleware
# =========================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================================================
# URLs & Templates
# =========================================================

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # Project-level templates directory.
        "DIRS": [BASE_DIR / "templates"],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI entry point used by Gunicorn on Render.
WSGI_APPLICATION = "config.wsgi.application"


# =========================================================
# Database
# =========================================================

# Render provides DATABASE_URL; local development uses the existing DB_* variables.
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Production database on Render.
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Local PostgreSQL database.
    DATABASES = {
        "default": dj_database_url.config(
            default=(
                f"postgresql://{os.getenv('DB_USER')}:"
                f"{os.getenv('DB_PASSWORD')}@"
                f"{os.getenv('DB_HOST')}:"
                f"{os.getenv('DB_PORT')}/"
                f"{os.getenv('DB_NAME')}"
            ),
            conn_max_age=600,
        )
    }


# =========================================================
# Password Validation
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =========================================================
# Authentication
# =========================================================

# Enable normal Django login and Django Allauth authentication.
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Django Sites configuration.
SITE_ID = 1

# Login and logout redirects.

LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/welcome/"
LOGIN_URL = "/login/"


# =========================================================
# Google Authentication
# =========================================================

# Store Google OAuth tokens because DevForge uses the token for Gmail features.
SOCIALACCOUNT_STORE_TOKENS = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # Profile information + Gmail sending permission.
        "SCOPE": [
            "profile",
            "email",
            "openid",
            "https://www.googleapis.com/auth/gmail.send",
        ],

        # Offline access allows DevForge to use a refresh token when required.
        "AUTH_PARAMS": {
            "access_type": "offline",
        },
    },
}


# =========================================================
# AI APIs
# =========================================================

# API keys are stored in environment variables, not in source code.
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


# =========================================================
# Internationalization
# =========================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True


# =========================================================
# Static Files
# =========================================================

STATIC_URL = "static/"

# Source directory for project static files.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# collectstatic stores production static files here.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves compressed static files in production.
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)


# =========================================================
# Media Files
# =========================================================

# User-uploaded files are stored here during local development.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================================================
# Email
# =========================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        "587",
    )
)

EMAIL_USE_TLS = (
    os.getenv(
        "EMAIL_USE_TLS",
        "True",
    )
    == "True"
)

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


# =========================================================
# Production Security
# =========================================================

# These settings are enabled only when DevForge runs in production.
if not DEBUG:
    SECURE_SSL_REDIRECT = True

    # Cookies are sent only over HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Render uses HTTPS behind a proxy.
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    # Basic browser security headers.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True

    # Console logging for production error debugging.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
    },
}