# Generated by Django 6.1 on 2026-08-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiinteraction',
            old_name='response_text',
            new_name='output_text',
        ),
    ]
