# Generated by Django 6.1 on 2026-08-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_email_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='recipients',
            new_name='to',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
